In [32]:
import numpy as np

def test_run():
    
    np.random.seed(693) # seed the random numbr generator
    a = np.random.randint(0, 10, size=(5,4)) # 5x4 random integers in [0,10]
    print('Array:\n', a)

    # Iterate over rows, to compute sum of each column
    print('Sum of array:\n', a.sum())
    
    # Iterate over rows, to compute sum of each column
    print('Sum of each column:\n', a.sum(axis=0))

    # Iterate over columns, to compute sum of each row
    print('Sum of each row:\n', a.sum(axis=1))
    
    # Statistics
    print('Minimum of each column:\n', a.min(axis=0))
    print('Maximum of each row:\n', a.max(axis=1))
    print('Mean of ndarray:\n', a.mean())
    print('Index of max.:', get_max_index(a))

    # Slicing
    print('Accessing element at position (3,2):', a[3,2])
    print('Accessing elements in a defined range:', a[0,1:3])  # Slicing
    print('Select columns 0 and 2 for every row:\n', a[:,0:3:2])  # Slice n:m:t, starts at n, stops before m, in t steps
    
    #Assigning values to an ndarray
    a[1,2]= 40
    a[3,:]=55
    print('Modified Array:\n', a)
    a[:, 3]= [1,2,3,4,5]
    print('Modified Array after asigning a list to a column:\n', a)
    
    #Accesing list of indices
    oned = np.random.rand(5)
    print(oned)
    indices = np.array([1,1,2,3])
    print('Passing a list to indices (1,1,2,3):\n',oned[indices])
    
    # Boolean or Masking index arrays
    b = np.array([(20,25,10,23,26,32,10,5,0),(0,2,50,20,0,1,28,5,0)])
    print('b array:\n',b)
    mean = b.mean()
    print('Mean:', mean)
    print('Values less than the mean:', b[b<mean])
    b[b<mean] = mean
    print('b array with mean replacing values below mean:\n',b)
    
    # Arithmetic operations
    c = np.array([(1,2,3,4,5),(10,20,30,40,50)])
    print('Original array c:\n', c)
    d = np.array([(100,200,300,400,500),(1,2,3,4,5)])
    print('Original array d:\n', d)
    
    print('Add c + d:\n', c+d)
    print('Multiply c and d:\n', c*d)  # Element-wise multiplication
    print('Divide c and d:\n', c / d)  # Element-wise division
    
def get_max_index(a):
    """Return the index of the maximum value in given 1D array."""
    return a.argmax() # TODO: Your code here  

   
if __name__ == "__main__":
    test_run()

Array:
 [[2 0 5 1]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]
Sum of array:
 79
Sum of each column:
 [25 15 25 14]
Sum of each row:
 [ 8 12 21 24 14]
Minimum of each column:
 [1 0 0 1]
Maximum of each row:
 [5 4 9 9 7]
Mean of ndarray:
 3.95
Index of max.: 8
Accessing element at position (3,2): 7
Accessing elements in a defined range: [0 5]
Select columns 0 and 2 for every row:
 [[2 5]
 [1 4]
 [9 9]
 [9 7]
 [4 0]]
Modified Array:
 [[ 2  0  5  1]
 [ 1  3 40  4]
 [ 9  2  9  1]
 [55 55 55 55]
 [ 4  7  0  3]]
Modified Array after asigning a list to a column:
 [[ 2  0  5  1]
 [ 1  3 40  2]
 [ 9  2  9  3]
 [55 55 55  4]
 [ 4  7  0  5]]
[0.31127579 0.62872047 0.07569968 0.54876981 0.53860522]
Passing a list to indices (1,1,2,3):
 [0.62872047 0.62872047 0.07569968 0.54876981]
b array:
 [[20 25 10 23 26 32 10  5  0]
 [ 0  2 50 20  0  1 28  5  0]]
Mean: 14.277777777777779
Values less than the mean: [10 10  5  0  0  2  0  1  5  0]
b array with mean replacing values below mean:
 [[20 25 14 23 26